OSError at line "86" in "/home/rakesh/git/scanproj/scanapp/scan_helper.py"nAttributeError at line "100" in "/home/rakesh/git/scanproj/scanapp/scan_helper.py"nOSError at line "86" in "/home/rakesh/git/scanproj/scanapp/scan_helper.py"nAttributeError at line "100" in "/home/rakesh/git/scanproj/scanapp/scan_helper.py"n